spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    properties:
      hibernate.format_sql: true

--- # local
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.h2.Driver
    hikari:
      jdbc-url: jdbc:h2:mem:testdb
      username: sa
      password:
  batch:
    jdbc:
      initialize-schema: embedded


--- # dev
spring:
  config:
    activate:
      on-profile: dev
  datasource-meta:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/springbatch?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123123
  datasource-datalog:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3307/datalog
    username: root
    password: 123123
  batch:
    jdbc:
      initialize-schema: always
#      table-prefix: LOG_BATCH
#    job:
#      enabled: false
#      names: ${job.name:NONE}

